### ISSUE TITLE
Fixef Function with Instruments

### ISSUE THREAD

**Issue by gorkembostanci** [ycroissant/plm#10]
Hello,

The fixef function gives the following error when instruments are used in plm function:

Error in tcrossprod(coef(object), as.matrix(object$model[, -1, drop = FALSE])) : 
  non-conformable arguments

I believe this is because the object 'as.matrix(object$model[, -1, drop = FALSE])' has the instruments in it. I think this wasn't an issue before March.

Best,

**Comment by tappek** [comment]
Thank your for reporting. This bug is in since 2.4-0 when fixed was fixed for the two-way FE model.
You can workaround this by estimating a one-way model with dummies for the other dimension.

**Comment by gorkembostanci** [comment]
I see, thank you!

**Comment by tappek** [comment]
This is fixed in the development version since a few days in rev. 1293, https://r-forge.r-project.org/R/?group_id=406.

Install via `install.packages("plm", repos="http://R-Forge.R-project.org")`.

Be sure to check out the fast mode of the package by setting `options("plm.fast" = TRUE)`.

[While fixing this bug, I found an issue in package `fixest:fixef()` related to this (https://github.com/lrberge/fixest/issues/190) and found a somewhat suprisingly dynamic setting of the reference level in `lfe:getfe()` (https://github.com/sgaure/lfe/issues/52).]

**Comment by tappek** [comment]
plm version 2.4-2 now on CRAN (2021-09-21) containing this fix
