### ISSUE TITLE
pmg slow

### ISSUE THREAD

**Issue by waynelapierre** [ycroissant/plm#7]
I found the pmg function to be really slow even for medium-sized data. Have you considered enhancing pmg or the other functions in plm with C++ codes, just like the fixest package?

**Comment by tappek** [comment]
`pmg` benefits from the fast mode which can be switched on by `options("plm.fast" = TRUE)` (see also the NEWS of the package). At some point in time, the fast mode will be the default but for now it needs to be switched on explictly.

(See also this old thread about `pmg` in which you were involved: https://github.com/SebKrantz/collapse/issues/120)

**Comment by tappek** [comment]
Since yesterday, `pmg` should be a little faster even without the fast mode (developement version revision 1283). 
Available here: https://r-forge.r-project.org/R/?group_id=406
Install via `install.packages("plm", repos="http://R-Forge.R-project.org")`

**Comment by tappek** [comment]
`pmg` should now be faster due to optimized data processing. To be included in the next CRAN version. One can install the development version which includes the speed-up like this:

`# install.packages("remotes") # remove '#' if pkg 'remotes' is not installed
remotes::install_github("ycroissant/plm")`

**Comment by tappek** [comment]
Released on CRAN as plm 2.6-2.
